"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., Hero.v1.tsx).
 * To stop versioning this component, run: npx uifork promote Hero <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./Hero.versions"

export default function Hero(props: any) {
  return (
    <ForkedComponent
      id="Hero"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
