/**
 * THIS FILE IS GENERATED by uifork.
 * @uifork-export default
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote Hero <version-id>
 */
import HeroV1 from "./Hero.v1"
import HeroV2 from "./Hero.v2"
export const VERSIONS = {
  "v1": {
    render: HeroV1,
    label: "",
  },
  "v2": {
    render: HeroV2,
    label: "",
  },
}
